ALTER TABLE participants ADD COLUMN IF NOT EXISTS skipped BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS skip_until TIMESTAMPTZ;
ALTER TABLE participants ADD COLUMN IF NOT EXISTS original_position INT;